# Generated by Django 3.1.1 on 2020-12-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201207_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_project',
            name='paragraph',
            field=models.TextField(max_length=2000, verbose_name='Current Paragraph'),
        ),
        migrations.AlterField(
            model_name='project_post',
            name='body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='slideshow_project',
            name='paragraph',
            field=models.TextField(max_length=2000, verbose_name='Slide Paragraph'),
        ),
    ]
