# Generated by Django 3.1.1 on 2020-12-06 22:48

from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_edu', models.CharField(max_length=255, verbose_name='Type')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('school', models.CharField(max_length=255, verbose_name='School')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='External_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=100, verbose_name='Link Name')),
                ('link_url', models.CharField(max_length=255, verbose_name='Link URL')),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page Name')),
                ('active', models.BooleanField(default=False)),
                ('link_url', models.CharField(max_length=255, verbose_name='Django Link')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Resume_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resume Title')),
                ('file_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Type')),
                ('res_file', models.FileField(upload_to=myadmin.models.resume_upload_location, verbose_name='Resume')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('profile_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_profile_location', to='myadmin.page')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(height_field='height', upload_to=myadmin.models.upload_location, verbose_name='Image', width_field='width')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_image_location', to='myadmin.page')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.TextField(max_length=255, verbose_name='Hobby')),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('external_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hobby_external_link', to='myadmin.external_link')),
                ('internal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hobby_on_page', to='myadmin.page')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_location', models.CharField(max_length=100, verbose_name='Location')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('entry', models.TextField(max_length=5000, verbose_name='Entry')),
                ('image', models.ImageField(blank=True, null=True, upload_to=myadmin.models.entry_upload_location, verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Alt')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('active', models.BooleanField(default=False)),
                ('entry_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_entry_location', to='myadmin.page')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.TextField(verbose_name='Accomplishment')),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('external_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accomplishment_external_link', to='myadmin.external_link')),
                ('internal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accomplishment_on_page', to='myadmin.page')),
            ],
            options={
                'verbose_name': 'Accomplishment',
                'verbose_name_plural': 'Accomplishments',
            },
        ),
    ]
