# Generated by Django 3.1.1 on 2020-12-07 09:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='acc_name',
            field=tinymce.models.HTMLField(verbose_name='Accomplishment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby_name',
            field=tinymce.models.HTMLField(max_length=255, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
    ]
