# Generated by Django 3.1.1 on 2020-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20201207_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
