# Generated by Django 3.1.1 on 2020-12-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_entry_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='acc_name',
            field=models.TextField(verbose_name='Accomplishment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry',
            field=models.TextField(max_length=5000, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby_name',
            field=models.TextField(max_length=255, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
